name: Terraform Deploy

on:
  push:
    branches:
    - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
        aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
        aws-region: '${{ secrets.AWS_REGION }}'
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Initialize Terraform
      run: terraform -chdir="./terraform" init -backend-config="bucket=s310312024-001"
        -backend-config="key=terraform.tfstate"
        -backend-config="region=eu-central-1"

    - name: Terraform lint
      run: tflint

    - name: Plan Terraform changes
      run: terraform -chdir="./terraform" plan  -var-file="terraform.tfvars"
        -out=tfplan

    - name: Apply Terraform changes
      run: terraform -chdir="./terraform" apply -var-file="terraform.tfvars"
        --auto-approve

    - name: Destroy Terraform-managed infrastructure
      run: terraform -chdir="./terraform" destroy -var-file="terraform.tfvars"
        --auto-approve

    - name: Clean up
      run: rm ./terraform/tfplan
